### ISSUE TITLE
Add lineageos for microg and nanodroid to android guide

### ISSUE THREAD

**Issue by gsstudios** [PwOSS/Guideline#4]
Since the main goal of the Android guide is to avoid proprietary apps such as the play store, and to rely on open-source alternatives, I think it would be great to reference some awesome projects that are available to the public. 

This includes:
1. [LineageOS for MicroG](https://lineage.microg.org/), **and**
2. [Nanodroid](https://forum.xda-developers.com/apps/magisk/module-nanomod-5-0-20170405-microg-t3584928)

LineageOS for MicroG is a LineageOS fork with all of the MicroG components already baked in. Why was this fork required? Because package spoofing (IIRC) had to be enabled, and the LOS team strictly forbids such a feature. 

Nanodroid allows the option to install the Play Store as well in-case the user still needs it, but handles the bulk of the install as a Magisk module and can be removed with ease.

**Comment by DanSman** [comment]
That's a good idea.

Maybe we add an extra chapter under "Important" only for microG and putt all info about microG in there instead of under the App Store - chapter which is wrong anyway. 

Not sure about Nanodroid. I use it only for microG but as you know it's much more. 

We could also do an extra chapter only for ...
> to reference some awesome projects

I'm actually not happy with the whole chapter-structure of the Android guide. Something seems to be wrong for me. Maybe we change it generally?

**Comment by gsstudios** [comment]
I think changing it generally (adding a new chapter, etc) would be the right approach because I too find that the Android guide could use a bit of love :)

**Comment by DanSman** [comment]
Yeah, that would be great. Maybe we swap grav to something else too. I don't like that all chapters are always open. But should be possible to change it at grav as well. I haven't checked it properly yet.

What do you think about a tree like this:

Android
    ├── Good to know
    │   ├── Bootloader
    │   ├── Custom ROMs
    │   ├── Recovery
    │   └── Root
    ├── Projects
    │   ├── F-Droid
    │   ├── Magisk
    │   ├── microG
    │   └── NanoDroid
    ├── ROMs
    │   ├── LineageOS
    │   ├── RRemix
    │   └── etc.
    ├── Supported Phones
    │   └── 
    ├── Requirements
    │   └── 
    ├── HowTo
    └   └── 

It doesn't "catch" me as well :D But something like this? 

Actually, we could change all the chapter-structure. But let's stick to Android for now ;)

**Comment by gsstudios** [comment]
The structure seems all good to me :)

I could add a little detail on SOCs and how they affect custom ROM development (e.g. Mediatek bad, Qualcomm snapdragon good, etc). Maybe under supported phone section or bootloader...

Also, I think we should emphasize more how data loss/device brick/etc can occur in the case of the unexpected, and how responsibility is entirely on the user.

**Comment by DanSman** [comment]
Yep, sounds good ;)

Right. They need to know it. Maybe we add brick etc to "Good to know".

By the way, I just changed the folder structure and the "subsubpage". 
If someone like to know how - [https://github.com/getgrav/grav-theme-learn2/issues/15](https://github.com/getgrav/grav-theme-learn2/issues/15)
It isn't so confusing anymore, I think.
